# Generated by Django 3.2.15 on 2022-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('numb', models.DecimalField(decimal_places=6, max_digits=21)),
                ('idcast', models.IntegerField()),
                ('iduser', models.IntegerField()),
            ],
            options={
                'db_table': 'prctmp',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=50)),
                ('unit2', models.CharField(max_length=50)),
                ('numb', models.IntegerField()),
                ('box', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pric', models.IntegerField()),
                ('pic_path', models.ImageField(null=True, upload_to='products')),
                ('mainid', models.IntegerField()),
                ('idanbar', models.IntegerField()),
            ],
            options={
                'db_table': 'prc',
            },
        ),
    ]
