# Generated by Django 3.2.15 on 2022-11-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pric',
            new_name='price1',
        ),
    ]
