# Generated by Django 4.0.7 on 2022-09-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic_path',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
