# Generated by Django 4.0.7 on 2022-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0002_rename_pric_product_price1'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImage', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'sliderImage',
            },
        ),
    ]
