# Generated by Django 4.0.7 on 2022-09-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0002_product_pic_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('numb', models.DecimalField(decimal_places=6, max_digits=21)),
                ('idcast', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=21)),
                ('box', models.IntegerField()),
                ('pric', models.DecimalField(decimal_places=6, max_digits=21)),
                ('numfacto', models.CharField(max_length=15)),
                ('dat', models.DateTimeField()),
                ('idtot', models.IntegerField()),
                ('stut', models.IntegerField()),
                ('mainid', models.IntegerField()),
                ('idanbar', models.IntegerField()),
                ('ptk', models.DecimalField(decimal_places=6, max_digits=21)),
                ('tp', models.IntegerField()),
                ('wi', models.DecimalField(decimal_places=6, max_digits=21)),
                ('ag', models.BooleanField()),
                ('yad', models.CharField(max_length=250)),
                ('per_ma', models.DecimalField(decimal_places=6, max_digits=21)),
                ('per_av', models.DecimalField(decimal_places=6, max_digits=21)),
                ('per_visitor', models.DecimalField(decimal_places=6, max_digits=21)),
                ('lastprice', models.DecimalField(decimal_places=6, max_digits=21)),
                ('euprice', models.DecimalField(decimal_places=6, max_digits=21)),
                ('exp_dat', models.CharField(max_length=10)),
                ('aghsati', models.BooleanField()),
                ('day_baz', models.IntegerField()),
                ('idmfprc', models.IntegerField()),
                ('bachnumber', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'prctmp',
            },
        ),
    ]
