# Generated by Django 4.0.7 on 2022-11-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0003_sliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='sliderImage',
            field=models.ImageField(max_length=250, null=True, upload_to='sliderImage'),
        ),
        migrations.AlterModelTable(
            name='sliderimage',
            table='slider_store',
        ),
    ]
