# Generated by Django 4.0.7 on 2022-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vi_numb',
        ),
        migrations.AddField(
            model_name='order',
            name='iduser',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
