# Generated by Django 4.0.7 on 2023-01-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0004_alter_sliderimage_sliderimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='getFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=250, null=True)),
                ('kalanam', models.CharField(max_length=250, null=True)),
                ('idcast', models.IntegerField()),
                ('codekala', models.IntegerField()),
                ('dat', models.DateTimeField()),
                ('tim', models.DateTimeField()),
                ('numb', models.DecimalField(decimal_places=6, max_digits=21)),
                ('price', models.DecimalField(decimal_places=6, max_digits=21)),
                ('ptk', models.DecimalField(decimal_places=6, max_digits=21)),
            ],
            options={
                'db_table': 'web_factor',
            },
        ),
    ]
