# Generated by Django 4.0.7 on 2022-10-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0005_remove_product_add1_remove_product_add2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ag',
        ),
        migrations.RemoveField(
            model_name='order',
            name='aghsati',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bachnumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='box',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='day_baz',
        ),
        migrations.RemoveField(
            model_name='order',
            name='euprice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exp_dat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='idanbar',
        ),
        migrations.RemoveField(
            model_name='order',
            name='idmfprc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='idtot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastprice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mainid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numfacto',
        ),
        migrations.RemoveField(
            model_name='order',
            name='per_av',
        ),
        migrations.RemoveField(
            model_name='order',
            name='per_ma',
        ),
        migrations.RemoveField(
            model_name='order',
            name='per_visitor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pric',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ptk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stut',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wi',
        ),
        migrations.RemoveField(
            model_name='order',
            name='yad',
        ),
    ]
