# Generated by Django 4.0.7 on 2022-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0006_remove_order_ag_remove_order_aghsati_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
