# Generated by Django 4.0.7 on 2022-10-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0007_product_mainid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idanbar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
