# Generated by Django 4.0.7 on 2022-10-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0008_product_idanbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numb',
            field=models.IntegerField(),
        ),
    ]
