# Generated by Django 4.0.7 on 2022-10-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0009_alter_product_numb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pric',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
