# Generated by Django 4.0.7 on 2022-10-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopProduct', '0010_alter_product_pric_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pric',
            new_name='price1',
        ),
    ]
