"""
Django settings for SabaShop project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7emtqv#e$ik5bh4xkvqg7t@@2go&(s4mt17f9h*8+4n0s!koce'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.1.150","127.0.0.1","5.202.251.165"]


# Application definition


INSTALLED_APPS = [
    'django.contrib.auth',  # ! remove it for migrate then take it back
    'django.contrib.contenttypes',  # ! remove it for migrate then take it back
    'django.contrib.staticfiles',
    'rest_framework',
    "corsheaders",
    # * Apps
    'SabaShopUser',
    'SabaShopProduct',
    'SabaShopCategory',
    # * cleanUp must be last item
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'SabaShop.urls'
CORS_ALLOW_ALL_ORIGINS = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',

            ],
        },
    },
]

WSGI_APPLICATION = 'SabaShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'SabaShopDB111',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
#         'PORT': '3306',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'SabaShopDB111',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
#         'PORT': '3306',
#     }
# }
DATABASES = {
    'default': {
        'NAME': 'userpda1',
        'ENGINE': 'mssql',
        'HOST': 'PC2\SERVER_SABA',
        'USER': 'sa',
        'PASSWORD': '_*_100',
        'OPTIONS': {
        'driver':"ODBC Driver 13 for SQL Server",

    },
    # },
    #     'User': {
    #     'NAME': 'useracount',
    #     'ENGINE': 'mssql',
    #     'HOST': 'DESKTOP-0BES37O\SERVER_SABA',
    #     'USER': 'sa',
    #     'PASSWORD': '_*_100',
    #     'OPTIONS': {
    #     'Persist Security Info': True,
    # },
    }
    
    
    }
    
#     }
#     }
#     #     'default': {
#     #     'NAME': 'SabaShopTest',
#     #     'ENGINE': 'mssql',
#     #     'HOST': 'S-ARAB\SUB',
#     #     'USER': 'sa',
#     #     'PASSWORD': '_*_100',
#     #     'OPTIONS': {
#     #     'Persist Security Info': True,
#     # },
#     }
# }
    #     'TB_USER': {
    #     'NAME': 'useracount',
    #     'ENGINE': 'mssql',
    #     'HOST': 'DESKTOP-0BES37O\SERVER_SABA',
    #     'USER': 'sa',
    #     'PASSWORD': '_*_100',
    # }

# DATABASES = {
#     'default': {
#         'NAME': 'visitir1_salse_visitor',
#         'ENGINE': 'mssql',
#         'HOST': '89.32.251.8,9992',
#         'USER': 'user1',
#         'PASSWORD': '_*_100S',
#     }
# }
























# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = "assets"
MEDIA_ROOT = "../sabapayton/static"
MEDIA_URL = "media/"
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# DATABASE_ROUTERS = ['authRouter.authRouter']