# Generated by Django 3.2.15 on 2022-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=50)),
                ('pic_path', models.ImageField(null=True, upload_to='category1')),
            ],
            options={
                'db_table': 'kalagroup',
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=50)),
                ('rowv', models.IntegerField()),
                ('pic_path', models.ImageField(null=True, upload_to='category2')),
            ],
            options={
                'db_table': 'kalagroup2',
            },
        ),
    ]
