# Generated by Django 4.0.7 on 2022-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=50)),
                ('stut', models.IntegerField()),
                ('idmoin_seall', models.IntegerField()),
                ('idmoin_bay', models.IntegerField()),
                ('idmoin_rseall', models.IntegerField()),
                ('idmoin_rbay', models.IntegerField()),
                ('idmoin_takhseall', models.IntegerField()),
                ('idmoin_takhbay', models.IntegerField()),
                ('idmoin_avma', models.IntegerField()),
                ('idmoin_f_rafta', models.IntegerField()),
                ('idmoin_sakhta', models.IntegerField()),
                ('idmoin_dar_j', models.IntegerField()),
                ('idmoin_sar', models.IntegerField()),
                ('idmoin_dast', models.IntegerField()),
                ('ver', models.IntegerField()),
                ('idmoin_mojodi', models.IntegerField()),
                ('ckcg', models.IntegerField()),
                ('rowv', models.IntegerField()),
            ],
            options={
                'db_table': 'kalagroup',
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=50)),
                ('stut', models.IntegerField()),
                ('ver', models.IntegerField()),
                ('rowv', models.IntegerField()),
            ],
            options={
                'db_table': 'kalagroup2',
            },
        ),
    ]
