# Generated by Django 4.0.7 on 2022-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pic_path',
            field=models.ImageField(null=True, upload_to='category1'),
        ),
        migrations.AddField(
            model_name='category2',
            name='pic_path',
            field=models.ImageField(null=True, upload_to='category2'),
        ),
    ]
