# Generated by Django 4.0.7 on 2022-10-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopCategory', '0002_category_pic_path_category2_pic_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ckcg',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_avma',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_bay',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_dar_j',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_dast',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_f_rafta',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_mojodi',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_rbay',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_rseall',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_sakhta',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_sar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_seall',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_takhbay',
        ),
        migrations.RemoveField(
            model_name='category',
            name='idmoin_takhseall',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rowv',
        ),
        migrations.RemoveField(
            model_name='category',
            name='stut',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ver',
        ),
        migrations.RemoveField(
            model_name='category2',
            name='rowv',
        ),
        migrations.RemoveField(
            model_name='category2',
            name='stut',
        ),
        migrations.RemoveField(
            model_name='category2',
            name='ver',
        ),
    ]
