# Generated by Django 4.0.7 on 2022-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopCategory', '0003_remove_category_ckcg_remove_category_idmoin_avma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category2',
            name='rowv',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
