# Generated by Django 3.2.15 on 2022-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=11)),
                ('adr', models.CharField(max_length=150)),
                ('is_valid', models.BooleanField()),
            ],
            options={
                'db_table': 'webcast',
            },
        ),
        migrations.CreateModel(
            name='SUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nagative_forosh', models.BooleanField()),
                ('gfs14', models.BooleanField()),
            ],
            options={
                'db_table': 'userseting',
            },
        ),
    ]
