# Generated by Django 4.0.7 on 2022-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('yallowuser', models.BooleanField()),
                ('idprofile', models.IntegerField()),
                ('id_last_sandogh', models.IntegerField()),
                ('id_client', models.IntegerField()),
                ('ver', models.IntegerField()),
                ('stut', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
