# Generated by Django 4.0.7 on 2022-11-20 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopUser', '0002_alter_customeruser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='dat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
