# Generated by Django 4.0.7 on 2022-09-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopUser', '0003_usersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='per_takh_foroush',
            new_name='gfs14',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='nagative_forosh',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
