# Generated by Django 4.0.7 on 2022-11-08 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SabaShopUser', '0006_customeruser_adr_customeruser_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='dat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='customeruser',
            table='webcast_store',
        ),
    ]
